# Form implementation generated from reading ui file '.\AddFit_dialog_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddFit_Dialog(object):
    def setupUi(self, AddFit_Dialog):
        AddFit_Dialog.setObjectName("AddFit_Dialog")
        AddFit_Dialog.resize(416, 339)
        self.gridLayout = QtWidgets.QGridLayout(AddFit_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=AddFit_Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.listWidget_Models = QtWidgets.QListWidget(parent=AddFit_Dialog)
        self.listWidget_Models.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_Models.setObjectName("listWidget_Models")
        self.gridLayout.addWidget(self.listWidget_Models, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=AddFit_Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.listWidget_Datas = QtWidgets.QListWidget(parent=AddFit_Dialog)
        self.listWidget_Datas.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_Datas.setObjectName("listWidget_Datas")
        self.gridLayout.addWidget(self.listWidget_Datas, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AddFit_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(parent=AddFit_Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)

        self.retranslateUi(AddFit_Dialog)
        self.buttonBox.accepted.connect(AddFit_Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AddFit_Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddFit_Dialog)

    def retranslateUi(self, AddFit_Dialog):
        _translate = QtCore.QCoreApplication.translate
        AddFit_Dialog.setWindowTitle(_translate("AddFit_Dialog", "Dialog"))
        self.label.setText(_translate("AddFit_Dialog", "Datas :"))
        self.label_2.setText(_translate("AddFit_Dialog", "Models :"))
        self.label_3.setText(_translate("AddFit_Dialog", "Select data and model to fit with"))
