# Form implementation generated from reading ui file 'Layer_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LayerWidget(object):
    def setupUi(self, LayerWidget):
        LayerWidget.setObjectName("LayerWidget")
        LayerWidget.resize(168, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LayerWidget.sizePolicy().hasHeightForWidth())
        LayerWidget.setSizePolicy(sizePolicy)
        LayerWidget.setMinimumSize(QtCore.QSize(150, 150))
        LayerWidget.setMaximumSize(QtCore.QSize(168, 98))
        LayerWidget.setStyleSheet("#Layerform {\n"
"background-color: rgba(255,255,120, 255);\n"
"border: 2px solid #000000; /* 두께: 2px, 스타일: 실선, 색상: 검정 */\n"
"border-radius: 5px; /* 테두리 둥글게 설정 (옵션) */\n"
"}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LayerWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Layerform = QtWidgets.QWidget(parent=LayerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Layerform.sizePolicy().hasHeightForWidth())
        self.Layerform.setSizePolicy(sizePolicy)
        self.Layerform.setMinimumSize(QtCore.QSize(150, 130))
        self.Layerform.setBaseSize(QtCore.QSize(0, 0))
        self.Layerform.setObjectName("Layerform")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Layerform)
        self.verticalLayout.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_LayerName = EditableLabel(parent=self.Layerform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_LayerName.sizePolicy().hasHeightForWidth())
        self.label_LayerName.setSizePolicy(sizePolicy)
        self.label_LayerName.setObjectName("label_LayerName")
        self.horizontalLayout.addWidget(self.label_LayerName)
        self.pushButton_DeleteLayer = QtWidgets.QPushButton(parent=self.Layerform)
        self.pushButton_DeleteLayer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_DeleteLayer.sizePolicy().hasHeightForWidth())
        self.pushButton_DeleteLayer.setSizePolicy(sizePolicy)
        self.pushButton_DeleteLayer.setMinimumSize(QtCore.QSize(16, 0))
        self.pushButton_DeleteLayer.setMaximumSize(QtCore.QSize(62, 16777215))
        self.pushButton_DeleteLayer.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_DeleteLayer.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/fugue-icons-3.5.6/icons/cross-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_DeleteLayer.setIcon(icon)
        self.pushButton_DeleteLayer.setFlat(True)
        self.pushButton_DeleteLayer.setObjectName("pushButton_DeleteLayer")
        self.horizontalLayout.addWidget(self.pushButton_DeleteLayer, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_isCoherent = QtWidgets.QPushButton(parent=self.Layerform)
        self.pushButton_isCoherent.setObjectName("pushButton_isCoherent")
        self.verticalLayout.addWidget(self.pushButton_isCoherent)
        self.pushButton_SetLayer = QtWidgets.QPushButton(parent=self.Layerform)
        self.pushButton_SetLayer.setFlat(False)
        self.pushButton_SetLayer.setObjectName("pushButton_SetLayer")
        self.verticalLayout.addWidget(self.pushButton_SetLayer)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_SaveLayer = QtWidgets.QPushButton(parent=self.Layerform)
        self.pushButton_SaveLayer.setObjectName("pushButton_SaveLayer")
        self.horizontalLayout_2.addWidget(self.pushButton_SaveLayer)
        self.pushButton_LoadLayer = QtWidgets.QPushButton(parent=self.Layerform)
        self.pushButton_LoadLayer.setObjectName("pushButton_LoadLayer")
        self.horizontalLayout_2.addWidget(self.pushButton_LoadLayer)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.Layerform)

        self.retranslateUi(LayerWidget)
        QtCore.QMetaObject.connectSlotsByName(LayerWidget)

    def retranslateUi(self, LayerWidget):
        _translate = QtCore.QCoreApplication.translate
        LayerWidget.setWindowTitle(_translate("LayerWidget", "Form"))
        self.pushButton_isCoherent.setText(_translate("LayerWidget", "Coherence : On"))
        self.pushButton_SetLayer.setText(_translate("LayerWidget", "Set Layer"))
        self.pushButton_SaveLayer.setText(_translate("LayerWidget", "Save"))
        self.pushButton_LoadLayer.setText(_translate("LayerWidget", "Load"))
from lib.CustomClass import EditableLabel
