# Form implementation generated from reading ui file '.\ParController_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ParContollerDockWidget(object):
    def setupUi(self, ParContollerDockWidget):
        ParContollerDockWidget.setObjectName("ParContollerDockWidget")
        ParContollerDockWidget.resize(115, 556)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParContollerDockWidget.sizePolicy().hasHeightForWidth())
        ParContollerDockWidget.setSizePolicy(sizePolicy)
        ParContollerDockWidget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        ParContollerDockWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_ParameterName = QtWidgets.QLabel(parent=self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ParameterName.setFont(font)
        self.label_ParameterName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ParameterName.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_ParameterName.setObjectName("label_ParameterName")
        self.verticalLayout.addWidget(self.label_ParameterName)
        self.label = QtWidgets.QLabel(parent=self.dockWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ParController_dial = QtWidgets.QDial(parent=self.dockWidgetContents)
        self.ParController_dial.setObjectName("ParController_dial")
        self.verticalLayout.addWidget(self.ParController_dial)
        self.ParController_verticalSlider = QtWidgets.QSlider(parent=self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ParController_verticalSlider.sizePolicy().hasHeightForWidth())
        self.ParController_verticalSlider.setSizePolicy(sizePolicy)
        self.ParController_verticalSlider.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.ParController_verticalSlider.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.ParController_verticalSlider.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ParController_verticalSlider.setMinimum(50)
        self.ParController_verticalSlider.setMaximum(150)
        self.ParController_verticalSlider.setSliderPosition(100)
        self.ParController_verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.ParController_verticalSlider.setInvertedAppearance(False)
        self.ParController_verticalSlider.setInvertedControls(False)
        self.ParController_verticalSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBothSides)
        self.ParController_verticalSlider.setTickInterval(10)
        self.ParController_verticalSlider.setObjectName("ParController_verticalSlider")
        self.verticalLayout.addWidget(self.ParController_verticalSlider)
        ParContollerDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(ParContollerDockWidget)
        QtCore.QMetaObject.connectSlotsByName(ParContollerDockWidget)

    def retranslateUi(self, ParContollerDockWidget):
        _translate = QtCore.QCoreApplication.translate
        ParContollerDockWidget.setWindowTitle(_translate("ParContollerDockWidget", "Parameter Controller"))
        self.label_ParameterName.setText(_translate("ParContollerDockWidget", "TextLabel"))
        self.label.setText(_translate("ParContollerDockWidget", "Controller"))
