# Form implementation generated from reading ui file 'Sample_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Sample(object):
    def setupUi(self, Sample):
        Sample.setObjectName("Sample")
        Sample.resize(271, 300)
        Sample.setStyleSheet("")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 120, 258))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_SampleStructure = QtWidgets.QVBoxLayout()
        self.verticalLayout_SampleStructure.setSpacing(0)
        self.verticalLayout_SampleStructure.setObjectName("verticalLayout_SampleStructure")
        self.horizontalLayout_2.addLayout(self.verticalLayout_SampleStructure)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout_Buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_Buttons.setObjectName("verticalLayout_Buttons")
        self.pushButton_AddLayer = QtWidgets.QPushButton(parent=self.dockWidgetContents)
        self.pushButton_AddLayer.setObjectName("pushButton_AddLayer")
        self.verticalLayout_Buttons.addWidget(self.pushButton_AddLayer)
        self.horizontalLayout.addLayout(self.verticalLayout_Buttons)
        Sample.setWidget(self.dockWidgetContents)

        self.retranslateUi(Sample)
        QtCore.QMetaObject.connectSlotsByName(Sample)

    def retranslateUi(self, Sample):
        _translate = QtCore.QCoreApplication.translate
        Sample.setWindowTitle(_translate("Sample", "Sample"))
        self.pushButton_AddLayer.setText(_translate("Sample", "Add Layer"))
